// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	types "github.com/compose-spec/compose-go/types"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	api "github.com/docker/compose/v2/pkg/api"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for Scheme.
const (
	Http  Scheme = "http"
	Https Scheme = "https"
)

// Defines values for StoreAppAuthorType.
const (
	ByNimoos  StoreAppAuthorType = "by_nimoos"
	Community StoreAppAuthorType = "community"
	Official  StoreAppAuthorType = "official"
	Unknown   StoreAppAuthorType = "unknown"
)

// Defines values for UpgradableAppInfoStatus.
const (
	Idle     UpgradableAppInfoStatus = "idle"
	Updating UpgradableAppInfoStatus = "updating"
)

// Defines values for WebAppGridItemAppType.
const (
	Container WebAppGridItemAppType = "container"
	Link      WebAppGridItemAppType = "link"
	V1app     WebAppGridItemAppType = "v1app"
	V2app     WebAppGridItemAppType = "v2app"
)

// Defines values for RequestComposeAppStatus.
const (
	RequestComposeAppStatusRestart RequestComposeAppStatus = "restart"
	RequestComposeAppStatusStart   RequestComposeAppStatus = "start"
	RequestComposeAppStatusStop    RequestComposeAppStatus = "stop"
)

// Defines values for SetComposeAppStatusJSONBody.
const (
	SetComposeAppStatusJSONBodyRestart SetComposeAppStatusJSONBody = "restart"
	SetComposeAppStatusJSONBodyStart   SetComposeAppStatusJSONBody = "start"
	SetComposeAppStatusJSONBodyStop    SetComposeAppStatusJSONBody = "stop"
)

// Defines values for ConvertParamsType.
const (
	Appfile ConvertParamsType = "appfile"
)

// AppStoreInfo > Do not mistake it as *information of AppStore* which does not exist.
type AppStoreInfo struct {
	Devices []DeviceStoreInfo `json:"devices" yaml:",omitempty"`
	Envs    []EnvStoreInfo    `json:"envs" yaml:",omitempty"`
	Image   string            `json:"image"`
	Ports   []PortStoreInfo   `json:"ports" yaml:",omitempty"`
	Volumes []VolumeStoreInfo `json:"volumes" yaml:",omitempty"`
}

// AppStoreMetadata defines model for AppStoreMetadata.
type AppStoreMetadata struct {
	ID        *int    `json:"id,omitempty"`
	StoreRoot *string `json:"store_root,omitempty"`
	URL       *string `json:"url,omitempty"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// CategoryInfo defines model for CategoryInfo.
type CategoryInfo struct {
	Count       *int    `json:"count,omitempty"`
	Description *string `json:"description,omitempty"`
	Font        *string `json:"font,omitempty"`
	ID          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type ComposeApp = types.Project

// ComposeAppContainers Schema for `ComposeAppContainersOK` response.
type ComposeAppContainers struct {
	Containers *map[string]ContainerSummary `json:"containers,omitempty"`
	Main       *string                      `json:"main,omitempty"`
}

// ComposeAppStoreInfo defines model for ComposeAppStoreInfo.
type ComposeAppStoreInfo struct {
	// Apps The key is the name of a container app, and the value is the StoreInfo of this container app.
	Apps *map[string]AppStoreInfo `json:"apps,omitempty" yaml:",omitempty"`

	// Architectures The architectures supported by the compose app. If the architecture of the host is not in this list, the compose app will not be installed.
	Architectures *[]string          `json:"architectures,omitempty" yaml:",omitempty"`
	Author        string             `json:"author"`
	Category      string             `json:"category"`
	Description   map[string]string  `json:"description"`
	Developer     string             `json:"developer"`
	Hostname      *string            `json:"hostname,omitempty" yaml:",omitempty"`
	Icon          string             `json:"icon"`
	Image         *map[string]string `json:"image,omitempty"`
	Index         string             `json:"index" yaml:",omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled *bool `json:"is_uncontrolled,omitempty" yaml:",omitempty"`

	// Main The main service is one of the services that the user will interact with.
	Main           *string  `json:"main,omitempty" yaml:",omitempty"`
	PortMap        string   `json:"port_map" mapstructure:"port_map" yaml:"port_map,omitempty"`
	Scheme         *Scheme  `json:"scheme,omitempty" yaml:",omitempty"`
	ScreenshotLink []string `json:"screenshot_link" mapstructure:"screenshot_link" yaml:"screenshot_link,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID       `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Tagline    map[string]string `json:"tagline"`
	Thumbnail  string            `json:"thumbnail"`
	Tips       TipsStoreInfo     `json:"tips"`
	Title      map[string]string `json:"title"`
}

// ComposeAppStoreInfoLists defines model for ComposeAppStoreInfoLists.
type ComposeAppStoreInfoLists struct {
	Installed *[]StoreAppID                   `json:"installed,omitempty"`
	List      *map[string]ComposeAppStoreInfo `json:"list,omitempty"`
}

// ComposeAppStoreTag defines model for ComposeAppStoreTag.
type ComposeAppStoreTag struct {
	Tag string `json:"tag"`
}

// ComposeAppValidationErrors for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
type ComposeAppValidationErrors struct {
	union json.RawMessage
}

// ComposeAppValidationErrorsPortsInUse This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsInUse struct {
	PortsInUse *struct {
		TCP *PortList `json:"TCP,omitempty"`
		UDP *PortList `json:"UDP,omitempty"`
	} `json:"ports_in_use,omitempty"`
}

// ComposeAppValidationErrorsPortsOutOfRange This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsOutOfRange struct {
	PortsOutOfRange *[]string `json:"ports_out_of_range,omitempty"`
}

// ComposeAppWithStoreInfo Schema for `ComposeAppOK` response.
//
// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
type ComposeAppWithStoreInfo struct {
	// Compose See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
	Compose *ComposeApp `json:"compose,omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled  *bool                `json:"is_uncontrolled,omitempty" yaml:",omitempty"`
	Status          *string              `json:"status,omitempty"`
	StoreInfo       *ComposeAppStoreInfo `json:"store_info,omitempty"`
	UpdateAvailable *bool                `json:"update_available,omitempty" yaml:",omitempty"`
}

// ContainerSummary See [Go Doc](https://pkg.go.dev/github.com/docker/compose/v2@v2.14.2/pkg/api#ContainerSummary) for the schema structure of `ContainerSummary`.
type ContainerSummary = api.ContainerSummary

// DeviceStoreInfo defines model for DeviceStoreInfo.
type DeviceStoreInfo struct {
	Container   *string            `json:"container,omitempty"`
	Description *map[string]string `json:"description,omitempty"`
}

// EnvStoreInfo defines model for EnvStoreInfo.
type EnvStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// GlobalSetting defines model for GlobalSetting.
type GlobalSetting struct {
	// Description description of the setting
	Description *string `json:"description,omitempty"`

	// Key key of the setting
	Key *string `json:"key,omitempty"`

	// Value value of the setting
	Value string `json:"value"`
}

// Info defines model for Info.
type Info struct {
	// Architecture current architecture
	Architecture *string `json:"architecture,omitempty"`
}

// PortList defines model for PortList.
type PortList = []string

// PortStoreInfo defines model for PortStoreInfo.
type PortStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// Scheme defines model for Scheme.
type Scheme string

// StoreAppAuthorType Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_nimoos`: The app is contributed by NimoOS team, i.e. `author` is `NimoOS Team`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_nimoos`
type StoreAppAuthorType string

// StoreAppID Store app ID of the compose app (unique across all app stores)
//
// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
type StoreAppID = string

// TipsStoreInfo defines model for TipsStoreInfo.
type TipsStoreInfo struct {
	BeforeInstall map[string]string `json:"before_install" mapstructure:"before_install" yaml:"before_install,omitempty"`
	Custom        *string           `json:"custom,omitempty"`
}

// UpgradableAppInfo Schema for `UpgradableAppListOK` response.
type UpgradableAppInfo struct {
	Icon   string                  `json:"icon"`
	Status UpgradableAppInfoStatus `json:"status"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      string      `json:"title"`

	// Version current version of the installed app
	Version string `json:"version"`
}

// UpgradableAppInfoStatus defines model for UpgradableAppInfo.Status.
type UpgradableAppInfoStatus string

// VolumeStoreInfo defines model for VolumeStoreInfo.
type VolumeStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// WebAppGridItem (internal use ONLY)
type WebAppGridItem struct {
	AppType WebAppGridItemAppType `json:"app_type"`

	// AuthorType Type of the author of the app
	//
	// - `official`: The app is contributed by the app owner, i.e. `author`` and `developer`` are the same.
	// - `by_nimoos`: The app is contributed by NimoOS team, i.e. `author` is `NimoOS Team`
	// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_nimoos`
	AuthorType *StoreAppAuthorType `json:"author_type,omitempty"`

	// Desktop true when the container declares nimoos.enable=true (desktop label spec)
	Desktop        *bool   `json:"desktop,omitempty"`
	Hostname       *string `json:"hostname,omitempty"`
	Icon           *string `json:"icon,omitempty"`
	Image          *string `json:"image,omitempty"`
	Index          *string `json:"index,omitempty"`
	IsUncontrolled *bool   `json:"is_uncontrolled,omitempty"`
	Name           *string `json:"name,omitempty"`
	Port           *string `json:"port,omitempty"`
	Scheme         *Scheme `json:"scheme,omitempty" yaml:",omitempty"`
	Status         *string `json:"status,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID        `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      *map[string]string `json:"title,omitempty"`

	// Widget widget declared via nimoos.widget.* labels (internal use ONLY)
	Widget *WebAppGridItemWidget `json:"widget,omitempty"`
}

// WebAppGridItemAppType defines model for WebAppGridItem.AppType.
type WebAppGridItemAppType string

// WebAppGridItemWidget widget declared via nimoos.widget.* labels (internal use ONLY)
type WebAppGridItemWidget struct {
	H *int `json:"h,omitempty"`

	// Maxh max resizable height in cells; absent = global default 4
	Maxh *int `json:"maxh,omitempty"`

	// Maxw max resizable width in cells; absent = global default 4
	Maxw *int `json:"maxw,omitempty"`

	// Minh min resizable height in cells; absent = global default 1
	Minh *int `json:"minh,omitempty"`

	// Minw min resizable width in cells; absent = global default 2
	Minw *int   `json:"minw,omitempty"`
	Path string `json:"path"`
	W    *int   `json:"w,omitempty"`
}

// AppStoreID defines model for AppStoreID.
type AppStoreID = int

// AppStoreURL defines model for AppStoreURL.
type AppStoreURL = string

// CheckPortConflict defines model for CheckPortConflict.
type CheckPortConflict = bool

// ComposeAppID defines model for ComposeAppID.
type ComposeAppID = string

// ContainerID defines model for ContainerID.
type ContainerID = string

// ContainerIDs defines model for ContainerIDs.
type ContainerIDs = string

// DeleteConfigFolder defines model for DeleteConfigFolder.
type DeleteConfigFolder = bool

// DryRun defines model for DryRun.
type DryRun = bool

// Force defines model for Force.
type Force = bool

// GlobalSettingKey defines model for GlobalSettingKey.
type GlobalSettingKey = string

// PullLatestImage defines model for PullLatestImage.
type PullLatestImage = bool

// StoreAppAuthorTypeFilter Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_nimoos`: The app is contributed by NimoOS team, i.e. `author` is `NimoOS Team`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_nimoos`
type StoreAppAuthorTypeFilter = StoreAppAuthorType

// StoreAppCategoryFilter defines model for StoreAppCategoryFilter.
type StoreAppCategoryFilter = string

// StoreAppIDString defines model for StoreAppIDString.
type StoreAppIDString = string

// StoreAppRecommendedFilter defines model for StoreAppRecommendedFilter.
type StoreAppRecommendedFilter = bool

// Uncontrolled defines model for Uncontrolled.
type Uncontrolled = bool

// AppStoreListOK defines model for AppStoreListOK.
type AppStoreListOK struct {
	Data *[]AppStoreMetadata `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// AppStoreRegisterOK defines model for AppStoreRegisterOK.
type AppStoreRegisterOK = BaseResponse

// AppStoreUnregisterOK defines model for AppStoreUnregisterOK.
type AppStoreUnregisterOK = BaseResponse

// CategoryListOK defines model for CategoryListOK.
type CategoryListOK struct {
	Data *[]CategoryInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppBadRequest defines model for ComposeAppBadRequest.
type ComposeAppBadRequest struct {
	// Data for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
	Data *ComposeAppValidationErrors `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppContainersOK defines model for ComposeAppContainersOK.
type ComposeAppContainersOK struct {
	// Data Schema for `ComposeAppContainersOK` response.
	Data *ComposeAppContainers `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppHealthCheckOK defines model for ComposeAppHealthCheckOK.
type ComposeAppHealthCheckOK = BaseResponse

// ComposeAppInstallOK defines model for ComposeAppInstallOK.
type ComposeAppInstallOK = BaseResponse

// ComposeAppListOK defines model for ComposeAppListOK.
type ComposeAppListOK struct {
	Data *map[string]ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppLogsOK defines model for ComposeAppLogsOK.
type ComposeAppLogsOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppOK defines model for ComposeAppOK.
type ComposeAppOK struct {
	// Data Schema for `ComposeAppOK` response.
	//
	// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
	Data *ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoListsOK defines model for ComposeAppStoreInfoListsOK.
type ComposeAppStoreInfoListsOK struct {
	Data *ComposeAppStoreInfoLists `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoOK defines model for ComposeAppStoreInfoOK.
type ComposeAppStoreInfoOK struct {
	Data *ComposeAppStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreTagOK defines model for ComposeAppStoreTagOK.
type ComposeAppStoreTagOK struct {
	Data *ComposeAppStoreTag `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppUninstallOK defines model for ComposeAppUninstallOK.
type ComposeAppUninstallOK = BaseResponse

// ComposeAppUpdateOK defines model for ComposeAppUpdateOK.
type ComposeAppUpdateOK = BaseResponse

// ComposeAppUpdateSettingsOK defines model for ComposeAppUpdateSettingsOK.
type ComposeAppUpdateSettingsOK = BaseResponse

// ContainerHealthCheckOK defines model for ContainerHealthCheckOK.
type ContainerHealthCheckOK = BaseResponse

// ContainerRecreateOK defines model for ContainerRecreateOK.
type ContainerRecreateOK = BaseResponse

// GetWebAppGridOK defines model for GetWebAppGridOK.
type GetWebAppGridOK struct {
	Data *[]WebAppGridItem `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingOK defines model for GlobalSettingOK.
type GlobalSettingOK struct {
	Data *GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingsOK defines model for GlobalSettingsOK.
type GlobalSettingsOK struct {
	Data *[]GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// InfoOK defines model for InfoOK.
type InfoOK = Info

// PullImagesOK defines model for PullImagesOK.
type PullImagesOK = BaseResponse

// RequestComposeAppStatusOK defines model for RequestComposeAppStatusOK.
type RequestComposeAppStatusOK = BaseResponse

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// UpgradableAppListOK defines model for UpgradableAppListOK.
type UpgradableAppListOK struct {
	Data *[]UpgradableAppInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// RequestComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type RequestComposeApp = ComposeApp

// RequestComposeAppStatus defines model for RequestComposeAppStatus.
type RequestComposeAppStatus string

// ComposeAppStoreInfoListParams defines parameters for ComposeAppStoreInfoList.
type ComposeAppStoreInfoListParams struct {
	// Category Category of the store app
	Category *StoreAppCategoryFilter `form:"category,omitempty" json:"category,omitempty"`

	// AuthorType Author type of the store app
	AuthorType *StoreAppAuthorTypeFilter `form:"author_type,omitempty" json:"author_type,omitempty"`

	// Recommend The store app is recommended
	Recommend *StoreAppRecommendedFilter `form:"recommend,omitempty" json:"recommend,omitempty"`
}

// RegisterAppStoreParams defines parameters for RegisterAppStore.
type RegisterAppStoreParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppParams defines parameters for InstallComposeApp.
type InstallComposeAppParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// UninstallComposeAppParams defines parameters for UninstallComposeApp.
type UninstallComposeAppParams struct {
	// DeleteConfigFolder Delete the config folder of the app
	DeleteConfigFolder *DeleteConfigFolder `form:"delete_config_folder,omitempty" json:"delete_config_folder,omitempty"`
}

// UpdateComposeAppParams defines parameters for UpdateComposeApp.
type UpdateComposeAppParams struct {
	Force *Force `form:"force,omitempty" json:"force,omitempty"`
}

// ApplyComposeAppSettingsParams defines parameters for ApplyComposeAppSettings.
type ApplyComposeAppSettingsParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// ComposeAppLogsParams defines parameters for ComposeAppLogs.
type ComposeAppLogsParams struct {
	// Lines Number of lines to show from the end of the logs for each compose app.
	//
	// - show all logs if `-1`
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// SetComposeAppStatusJSONBody defines parameters for SetComposeAppStatus.
type SetComposeAppStatusJSONBody string

// RecreateContainerByIDParams defines parameters for RecreateContainerByID.
type RecreateContainerByIDParams struct {
	// Pull Try to pull the latest image from the registry
	Pull  *PullLatestImage `form:"pull,omitempty" json:"pull,omitempty"`
	Force *Force           `form:"force,omitempty" json:"force,omitempty"`
}

// ConvertJSONBody defines parameters for Convert.
type ConvertJSONBody = map[string]interface{}

// ConvertParams defines parameters for Convert.
type ConvertParams struct {
	Type *ConvertParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// ConvertParamsType defines parameters for Convert.
type ConvertParamsType string

// PullImagesParams defines parameters for PullImages.
type PullImagesParams struct {
	// ContainerIds a list of comma separated container IDs
	ContainerIds *ContainerIDs `form:"container_ids,omitempty" json:"container_ids,omitempty"`
}

// RegisterAppStoreSyncParams defines parameters for RegisterAppStoreSync.
type RegisterAppStoreSyncParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppJSONRequestBody defines body for InstallComposeApp for application/json ContentType.
type InstallComposeAppJSONRequestBody = ComposeApp

// ApplyComposeAppSettingsJSONRequestBody defines body for ApplyComposeAppSettings for application/json ContentType.
type ApplyComposeAppSettingsJSONRequestBody = ComposeApp

// SetComposeAppStatusJSONRequestBody defines body for SetComposeAppStatus for application/json ContentType.
type SetComposeAppStatusJSONRequestBody SetComposeAppStatusJSONBody

// ConvertJSONRequestBody defines body for Convert for application/json ContentType.
type ConvertJSONRequestBody = ConvertJSONBody

// UpdateGlobalSettingJSONRequestBody defines body for UpdateGlobalSetting for application/json ContentType.
type UpdateGlobalSettingJSONRequestBody = GlobalSetting

// AsComposeAppValidationErrorsPortsInUse returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsInUse
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsInUse() (ComposeAppValidationErrorsPortsInUse, error) {
	var body ComposeAppValidationErrorsPortsInUse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsInUse overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsInUse performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsComposeAppValidationErrorsPortsOutOfRange returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsOutOfRange
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsOutOfRange() (ComposeAppValidationErrorsPortsOutOfRange, error) {
	var body ComposeAppValidationErrorsPortsOutOfRange
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsOutOfRange overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsOutOfRange performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

func (t ComposeAppValidationErrors) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComposeAppValidationErrors) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get app list from registered app stores
	// (GET /apps)
	ComposeAppStoreInfoList(ctx echo.Context, params ComposeAppStoreInfoListParams) error
	// Get the list of upgradable apps from installed app.
	// (GET /apps/upgradable)
	UpgradableAppList(ctx echo.Context) error
	// Get app info from registered app stores
	// (GET /apps/{id})
	ComposeAppStoreInfo(ctx echo.Context, id StoreAppIDString) error
	// Get compose details of an app from registered app stores
	// (GET /apps/{id}/compose)
	ComposeApp(ctx echo.Context, id StoreAppIDString) error
	// Get app stable version from registered app stores
	// (GET /apps/{id}/stable)
	ComposeAppMainStableTag(ctx echo.Context, id StoreAppIDString) error
	// Get server of app stable version from registered app stores
	// (GET /apps/{id}/stable/{serviceName})
	ComposeAppServiceStableTag(ctx echo.Context, id StoreAppIDString, serviceName string) error
	// Get the list of registered app stores
	// (GET /appstore)
	AppStoreList(ctx echo.Context) error
	// Register an app store
	// (POST /appstore)
	RegisterAppStore(ctx echo.Context, params RegisterAppStoreParams) error
	// Unregister an app store
	// (DELETE /appstore/{id})
	UnregisterAppStore(ctx echo.Context, id AppStoreID) error
	// Get the list of app categories
	// (GET /categories)
	CategoryList(ctx echo.Context) error
	// Get the list of installed compose apps
	// (GET /compose)
	MyComposeAppList(ctx echo.Context) error
	// Install a compose app
	// (POST /compose)
	InstallComposeApp(ctx echo.Context, params InstallComposeAppParams) error
	// Uninstall a compose app
	// (DELETE /compose/{id})
	UninstallComposeApp(ctx echo.Context, id ComposeAppID, params UninstallComposeAppParams) error
	// Get compose details of a locally installed app
	// (GET /compose/{id})
	MyComposeApp(ctx echo.Context, id ComposeAppID) error
	// Update container images of compose app to match the compose app in AppStore.
	// (PATCH /compose/{id})
	UpdateComposeApp(ctx echo.Context, id ComposeAppID, params UpdateComposeAppParams) error
	// Apply settings to a compose app
	// (PUT /compose/{id})
	ApplyComposeAppSettings(ctx echo.Context, id ComposeAppID, params ApplyComposeAppSettingsParams) error
	// Get the list of containers of a compose app
	// (GET /compose/{id}/containers)
	ComposeAppContainers(ctx echo.Context, id ComposeAppID) error
	// Check if the compose app is running healthy
	// (GET /compose/{id}/healthcheck)
	CheckComposeAppHealthByID(ctx echo.Context, id ComposeAppID) error
	// Get the logs of a compose app
	// (GET /compose/{id}/logs)
	ComposeAppLogs(ctx echo.Context, id ComposeAppID, params ComposeAppLogsParams) error
	// Start/restart/stop a compose app
	// (PUT /compose/{id}/status)
	SetComposeAppStatus(ctx echo.Context, id ComposeAppID) error
	// Recreate the container app
	// (PATCH /container/{id})
	RecreateContainerByID(ctx echo.Context, id ContainerID, params RecreateContainerByIDParams) error
	// Check if the container app is running healthy
	// (GET /container/{id}/healthcheck)
	CheckContainerHealthByID(ctx echo.Context, id ContainerID) error
	// Convert to compose app from another file format
	// (POST /convert)
	Convert(ctx echo.Context, params ConvertParams) error
	// Get all global settings
	// (GET /global)
	GetGlobalSettings(ctx echo.Context) error
	// Delete a global setting
	// (DELETE /global/{key})
	DeleteGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Get a global setting
	// (GET /global/{key})
	GetGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Update a global setting
	// (PUT /global/{key})
	UpdateGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Post a batch pull request specified images
	// (POST /image)
	PullImages(ctx echo.Context, params PullImagesParams) error
	// Get certain common information
	// (GET /info)
	Info(ctx echo.Context) error
	// (internal use ONLY)
	// (GET /web/appgrid)
	GetAppGrid(ctx echo.Context) error
	// Register an app store in Sync.
	// (POST /web/sync/appstore)
	RegisterAppStoreSync(ctx echo.Context, params RegisterAppStoreSyncParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ComposeAppStoreInfoList converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfoList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppStoreInfoListParams
	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", ctx.QueryParams(), &params.Category)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// ------------- Optional query parameter "author_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "author_type", ctx.QueryParams(), &params.AuthorType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter author_type: %s", err))
	}

	// ------------- Optional query parameter "recommend" -------------

	err = runtime.BindQueryParameter("form", true, false, "recommend", ctx.QueryParams(), &params.Recommend)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recommend: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfoList(ctx, params)
	return err
}

// UpgradableAppList converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradableAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpgradableAppList(ctx)
	return err
}

// ComposeAppStoreInfo converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfo(ctx, id)
	return err
}

// ComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeApp(ctx, id)
	return err
}

// ComposeAppMainStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppMainStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppMainStableTag(ctx, id)
	return err
}

// ComposeAppServiceStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppServiceStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "serviceName" -------------
	var serviceName string

	err = runtime.BindStyledParameterWithLocation("simple", false, "serviceName", runtime.ParamLocationPath, ctx.Param("serviceName"), &serviceName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceName: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppServiceStableTag(ctx, id, serviceName)
	return err
}

// AppStoreList converts echo context to params.
func (w *ServerInterfaceWrapper) AppStoreList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AppStoreList(ctx)
	return err
}

// RegisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStore(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStore(ctx, params)
	return err
}

// UnregisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) UnregisterAppStore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id AppStoreID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UnregisterAppStore(ctx, id)
	return err
}

// CategoryList converts echo context to params.
func (w *ServerInterfaceWrapper) CategoryList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CategoryList(ctx)
	return err
}

// MyComposeAppList converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeAppList(ctx)
	return err
}

// InstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) InstallComposeApp(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InstallComposeAppParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InstallComposeApp(ctx, params)
	return err
}

// UninstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UninstallComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UninstallComposeAppParams
	// ------------- Optional query parameter "delete_config_folder" -------------

	err = runtime.BindQueryParameter("form", true, false, "delete_config_folder", ctx.QueryParams(), &params.DeleteConfigFolder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter delete_config_folder: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UninstallComposeApp(ctx, id, params)
	return err
}

// MyComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeApp(ctx, id)
	return err
}

// UpdateComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateComposeAppParams
	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateComposeApp(ctx, id, params)
	return err
}

// ApplyComposeAppSettings converts echo context to params.
func (w *ServerInterfaceWrapper) ApplyComposeAppSettings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyComposeAppSettingsParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ApplyComposeAppSettings(ctx, id, params)
	return err
}

// ComposeAppContainers converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppContainers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppContainers(ctx, id)
	return err
}

// CheckComposeAppHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckComposeAppHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckComposeAppHealthByID(ctx, id)
	return err
}

// ComposeAppLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppLogsParams
	// ------------- Optional query parameter "lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "lines", ctx.QueryParams(), &params.Lines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lines: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppLogs(ctx, id, params)
	return err
}

// SetComposeAppStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetComposeAppStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetComposeAppStatus(ctx, id)
	return err
}

// RecreateContainerByID converts echo context to params.
func (w *ServerInterfaceWrapper) RecreateContainerByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RecreateContainerByIDParams
	// ------------- Optional query parameter "pull" -------------

	err = runtime.BindQueryParameter("form", true, false, "pull", ctx.QueryParams(), &params.Pull)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pull: %s", err))
	}

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RecreateContainerByID(ctx, id, params)
	return err
}

// CheckContainerHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckContainerHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckContainerHealthByID(ctx, id)
	return err
}

// Convert converts echo context to params.
func (w *ServerInterfaceWrapper) Convert(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ConvertParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Convert(ctx, params)
	return err
}

// GetGlobalSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSettings(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSettings(ctx)
	return err
}

// DeleteGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteGlobalSetting(ctx, key)
	return err
}

// GetGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSetting(ctx, key)
	return err
}

// UpdateGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateGlobalSetting(ctx, key)
	return err
}

// PullImages converts echo context to params.
func (w *ServerInterfaceWrapper) PullImages(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PullImagesParams
	// ------------- Optional query parameter "container_ids" -------------

	err = runtime.BindQueryParameter("form", true, false, "container_ids", ctx.QueryParams(), &params.ContainerIds)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter container_ids: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PullImages(ctx, params)
	return err
}

// Info converts echo context to params.
func (w *ServerInterfaceWrapper) Info(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Info(ctx)
	return err
}

// GetAppGrid converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppGrid(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAppGrid(ctx)
	return err
}

// RegisterAppStoreSync converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStoreSync(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreSyncParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStoreSync(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/apps", wrapper.ComposeAppStoreInfoList)
	router.GET(baseURL+"/apps/upgradable", wrapper.UpgradableAppList)
	router.GET(baseURL+"/apps/:id", wrapper.ComposeAppStoreInfo)
	router.GET(baseURL+"/apps/:id/compose", wrapper.ComposeApp)
	router.GET(baseURL+"/apps/:id/stable", wrapper.ComposeAppMainStableTag)
	router.GET(baseURL+"/apps/:id/stable/:serviceName", wrapper.ComposeAppServiceStableTag)
	router.GET(baseURL+"/appstore", wrapper.AppStoreList)
	router.POST(baseURL+"/appstore", wrapper.RegisterAppStore)
	router.DELETE(baseURL+"/appstore/:id", wrapper.UnregisterAppStore)
	router.GET(baseURL+"/categories", wrapper.CategoryList)
	router.GET(baseURL+"/compose", wrapper.MyComposeAppList)
	router.POST(baseURL+"/compose", wrapper.InstallComposeApp)
	router.DELETE(baseURL+"/compose/:id", wrapper.UninstallComposeApp)
	router.GET(baseURL+"/compose/:id", wrapper.MyComposeApp)
	router.PATCH(baseURL+"/compose/:id", wrapper.UpdateComposeApp)
	router.PUT(baseURL+"/compose/:id", wrapper.ApplyComposeAppSettings)
	router.GET(baseURL+"/compose/:id/containers", wrapper.ComposeAppContainers)
	router.GET(baseURL+"/compose/:id/healthcheck", wrapper.CheckComposeAppHealthByID)
	router.GET(baseURL+"/compose/:id/logs", wrapper.ComposeAppLogs)
	router.PUT(baseURL+"/compose/:id/status", wrapper.SetComposeAppStatus)
	router.PATCH(baseURL+"/container/:id", wrapper.RecreateContainerByID)
	router.GET(baseURL+"/container/:id/healthcheck", wrapper.CheckContainerHealthByID)
	router.POST(baseURL+"/convert", wrapper.Convert)
	router.GET(baseURL+"/global", wrapper.GetGlobalSettings)
	router.DELETE(baseURL+"/global/:key", wrapper.DeleteGlobalSetting)
	router.GET(baseURL+"/global/:key", wrapper.GetGlobalSetting)
	router.PUT(baseURL+"/global/:key", wrapper.UpdateGlobalSetting)
	router.POST(baseURL+"/image", wrapper.PullImages)
	router.GET(baseURL+"/info", wrapper.Info)
	router.GET(baseURL+"/web/appgrid", wrapper.GetAppGrid)
	router.POST(baseURL+"/web/sync/appstore", wrapper.RegisterAppStoreSync)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9aXPcNrJ/BcXdqmen5pBsxYdepWplK3b07EQqHZtKLNcMhuyZQUQCXAAceeLSf3+F",
	"iyR4zC1L2ePDxhriaHQ3Gn2h8TUIWZIyClSK4PBrkGKOE5DA9V9HaXohGYeTY/VXBCLkJJWE0eAwODlG",
	"bIzkFBBOUyRUs6ATEPUpxXIadAKKEwgOAxIFnYDDvzLCIQoOJc+gE4hwCglWo8IXnKQxBId7nUDOU92D",
	"SpgAD+7uOjkIV+cf6zBcnX9sBeJfGfB5AUXG46Bx2mAqZSoO+/0JkdNs1AtZ0v+FJOwSwqn+x+lF1wER",
	"5CAKyQmdaAjfTiG8OWNcvmV0HJNQ1uHUTRAxkKaMyzLUoe0m0C2RU/1ZIBxzwNEcEYoyAb1rek27aKhw",
	"N0RdFOrx9ECut/4+xrHQDcQNSf3vps81bUGP/jpQPQauh4euCMY4i6Ujn8XCiLEYMDVoUHwk4ChNm7jl",
	"KE2R4RiMQtNSL/6J4osZjoFKJFn+KeXsDwglUtA93Y6tAjGnoZwqajVSj1GJCQXeBHX+UcFOqCbZMQtv",
	"gCOeUUkSxRHFTHuv4eXe+AC/jKLn4/DgeQQv8P4oPNiLDr4PX74ev/r+5fcHB7D//MXL1/D9aB8fvDzY",
	"e733/AC/DOHFs/2NFrpwSaK+JoxiIjQDhixJMBKg9ryESLFKvlrRxieuzYBEomVDwcHzV3uvXr7oRi+/",
	"f909GD170cXj/XH39YtX+ODF3ovo+evXjbQ4hhgkqG1EJu9YHAGvg2/aaEqEuiEa65alHdUCeqR7Dkyv",
	"gem1Jo8f8/l5RhuA4nPFEBoARSkQUm9mlkmEQ5nhOJ4j+BJmktAJIrKjNvU4i9GYcTTDMYmwGglhGiEJ",
	"QrWqbnnbChCj8dzf7Pkn1R2+QJhZBFlQWjd9xOcDntFmJOjhG7HwjvEQVNumMcf645ojvo/ZCMcXINXK",
	"P8C8juEPMHcUnujGSJjWzXvmBuYrSofTsx9/OToZHJ2dDD78+FsjW55lcfwRK7qcJHgCdeAu+VwJrzSL",
	"Yw1hrBsjolqjMWeJpcaECKlx1YQ41XtdvOlD6ShNjzI5ZfxynsI7EsumbWNaIDWGw6M+LRfsF6y7DPS0",
	"Zbj+zmEcHAZ/6xeaQ998Ff06QB6cb7GECePzNijd91VBDG37FkEUTrFspKiD5+T4wvxYg+TCzdx8amWU",
	"/CsDhEPOhDqs40L/EPd7XjnQz0GJb6ARRG3YvCxjEBGBeNGnBaF5i3U58Yqqk4GzOFaLq+mKVEhsN4eC",
	"JZeNdI5sv54T6eoPlACmaAZcKKlof+w4BcquRkg8io3QMxuuh4hUHwpIOuhECWJFnkwylKVKTPYQk1Pg",
	"t0SA7ZCVgK/K3fI3RMw6fPFLGU9wXHxrU0DLGGqkfBt27wzfgJBvWERAn+nn5odC6VI/qgmAav0Tp2lM",
	"Qn2q9P8QTJ9Zq23h0pBq5vJAc5zEPq/+DUVGHXK747ejnz8iC8c1FcBnJARxeE0R6vV613RlSeKBcdep",
	"KWbFZixPWdtid506qi4klplYC2FAsyQ4/BQIibmZxP1LSJYGn+s7dSHIwkBQA1ZTWqSMCvDsr49EyNMP",
	"a0GM4/h0HBx+WozlN1jAuZ0xuOt8DVLOUuDSclmEpR6MSEjEMoo5YH8GiXXHuxwrmHM8V0j53ICY0w9B",
	"yc4716ck8G+w3OXAXFH+GMBxx+Jfgg0csCd0zNZjgWKHvsGR3bUPt9jVhNM/c+X9R84ZF20rfIMjp477",
	"S82NNfGQlF1tsQWsqxLyJ8CxnGr3x0rLy0+Wr0ECQmhtO0iZkqirHhz+ipeDaHWTNbG/SwgeelvjKCJq",
	"Hhyfed9XY4pfiZwaJ6G/4dnoDwjlqozykU0edAMUKs11trf3PIzZRCiFRf3R5PZbaVGPf0dXiKeX1azz",
	"tTuclqIhn0Ax+l9AzPnwrkrsvNdfaIFrre0ST/4iS7vEK2/RK0oeXP5fabP0wQGw7jfxAIBYteIRawsW",
	"wnMIOTwEsd6D/BVGR2n6npPo0dsABagnEpL1rADPF/xYBY4H5BrrEY+edJWVrUO5DQ6/RZC4A6p5srMs",
	"jrU7/tvLqxaH0oO6CFybtSznRvmpLNXzwlLdDeIqg7qm5Yj5JrDm/XcGaHlE1+6ESuBUbQo+A67t/E0B",
	"dkMhMxYyg+0M+tbhXadfmHzHMhptCv8vTCIzwM5g9oZ0DTc//s122O12Ny0ujDP7iuIZJjEemZk3gdGO",
	"hMpD7QzolsGv0gnHkfrrEXgcVjqJPIjX9Sbm6PTzmNQoteiUMfLRMUOUSZQQIfGNDg1hgb4jdMx4YsLz",
	"bIzcSN+h2ykJpyhiIHQ3+EKE7AWd6opBB0BWXvSxbt/kTzFL7gRfugynpBuyCCZAu/BFctyVeKKHNtZ6",
	"0GGJmi2Vc40JoLPVIfiRznY8PXFR84YY56EJ3dU9LJ1AJ0KtDPYZ43LHcM9YnCVr0O6fuv1Ogbgrh4g+",
	"WUxagjoMFYB2cnb73AkkkRrVOTw6jE11NL0U4sijNYfVzUr0KZEQSpIs0el5HHB0SuN5JUPGpeup9U1Y",
	"18Y7T461TFNzDDhj0meASmJdN8GEBq0zFEyR8Xjj7L0+5uGUzKDPYSz6U8CR6Kt5e3+SdOnc/uKuzj8a",
	"6ngCr4bCXORXRY79gDjIjFOI0GiOhDmzBYnARro5ICIQpnMvyyxoDDZ6YZcaICHLqE+B5511SFuVsWUK",
	"vCM2Cn+MJUZvcHiTpUpOilXoOWYVuIKRHqDLwWVzLh3DMGo+wn5nW6Y1f5SBMqtaDoyfCNmQVgKAPrlI",
	"8EUKIRnbI/fzE8fJNpTeFSmEPcKe6iQxnQ2j5QwSkmehzLhO5BkWsw17QdX5bhdnf1T/Eb0zk1pZ/tYl",
	"iRIlClyLB91USRgsp8FhUNpcZejyPyasb3rctcS2GjBhFqPWNmyOhg2Ri4XXj9XQG3mzAIYd4SJLEszn",
	"iu4lZW3rVM7Dr3f1WEgn0HJu5XSfZgdzfXtjtds2RITvD+405BDdwFzJIcWCij1cOpRLFsVp2jGZi1NA",
	"Mxxn4Fp7R4+c2tScvJdJBykhvUCFwV5ts9kjzSQ1ETuwN6ZAhIZxFulkHZtSlOddNO6PtdUCfYpI0FtQ",
	"NGddeU2QyFK1vYyUr4DUQyc2qanUxaW/TZnQ+UlKv9SrIUIn73aqo5gcJ9VsBC4RSacylfH7KcBJ9OIg",
	"UCtIXhwoHSFXa2oy1aF69ZUEu1C5TM5hk6qALgEnTWpingPYLLBr7SvnWNuWqfUr8SnQQSaUDHP8qo9p",
	"zYiEZiwTaKzORMXOU84o+dOYDylnE46THjqRpW9gWgs0AnkLQJG8ZYhxlCgeV/jNJHDF1ogDjpEkCXSQ",
	"wGOI52pERRuITJZpyucKGJiD6KHfWMaR0uwUcPP8Dxwzao7rOctQBFrr0Kn3U6YoeWvUDmky7BiHqKN+",
	"U9qI+3WKOUTmsoJgCSi+5BFKMZdzIwim7BYR+T8CSY6pSIhUEDKl3CieIdpJAbIXNAnICGYQK0L49Lxo",
	"l5KdQO2T+pkdNKlw6xsvYVXfyc/piPb+EBHEZMZ7FGR/Mm1VPf+h5L4StaKfr6Svhu6lzUvKbaZt+LNm",
	"ZTUhnNAIvvgr7O8IdWKQLUwLVdygMz01W+hsaYn1ZgozIVnS0yLN5nkybtM8fanmkiatvLInj5KJXlZn",
	"UMur3GhJ7viui3z1Bdl8R7UCtctcFrPNgkRyiqX+JRPAjczWmwGH5rpARWD7qoFdoDuBZW1OioZupuFu",
	"CKivAyU49bnj1fNXB+uOn+A0V1t1jM4O3HEzu18qEGglBZZmnZtWuj0HoGLK5CAm9MYD/NO2O/c0BXqR",
	"AkSXIGS/mKq7b3fxfY3/TI+/+Lxe4+itEKOKs5wmlQ9V0mjLHqfpwNhfq1wLMOaVxJOY0K2l2zsO6iSE",
	"MONgzp2IqA6jTB+I3gkszAksGYubjx05zZIRxSTeqaz/P4jj+ZjQfj5874+0Ud5Lki7V1C9JKnzvkpEJ",
	"O1JimnK3fPeT1c465XsXZUlYPr3tydlpYC9H/zLW3WIsJtyxVJJBnxfkFDU4r5wSvLL3rsKjnp+5Eyi1",
	"e/tcucV5ck0ZN/WVSfNjwaOz/b3es8a7ImXaqW4+Cmupq2p5dL6Cl799jDPGpTihV9b7v8Ugp5k8HZ9j",
	"OoHg7nPVKh0rZcDeYhy2DzRU4gHQd9/9eH5+en7x3XfInr8jJiVLVG+KZ2RihMMI8167h6cQFSutvkFH",
	"IKKiFyyC3OgKIabGovNNWucXQSMWze1NztwUtJyvB6s7TrTLeEDU3m/wV16+PVvFz672nI4pHa/RvGbP",
	"N1r4ayK7xCWPG+MskwM2HnAHai6SluhV7ThyIbC1kOjne67olPNccdf0mi4KmA0bpN3QBsuIQH9kQqLC",
	"f1OKrHk37Jo8fvrjOteGvq0F0uasumeLROSXmQpO4hmlRilf6js3Whyx3LDBKWbu1A28mHgOiZm0BYgt",
	"lu3dcncO3GZn+3uGjllYeNfTm0lvwnoRzMohI3OLzfmz+7Nn/5g96+0f9J6p9n2ckr9Vp1vqlvebL3XO",
	"45T0akta6KPHKWn00NfW4tZg79j7AeaGUJEFouITUBiLOLlnl9r7sytkgpgtKpIXnl4V+Mvf7xnsS5IA",
	"+p1RWK5EFyD6EHyu5grWV1cB2Of20l+F48FdkS/dd0+BHp2go7MT9EFfkq8t76bp/v1Ncf++cdTqLfql",
	"gkcHCurzmPjBgpnETfeL+d9SldcUATATfbb5iQ2xk5KHuw5PmHEOVHrueQ8e51NfITCY60K7PP/NsGtv",
	"CTXZ/W6JX2GErk622w8Xufsnv4KuTXKdAmFu5No/tXiv38Pd6EhtKGJQVy5LhRSMWVwqQGKvkLPxmIQE",
	"x8NDdFlcW9cqgHVS2CiK+sJuKfAOIj3ooaEZcTjUXo1hblSrH7gp7SFwonSxLhqO5gNKEsbEwmlsEEUC",
	"TiqTqMbDUoxlqEcNWZJklMj5UuDzlnZcTOe6tVanbfCqQIVSokogG03KktI1CjpB3iLoBPkEQSfI6A1l",
	"t1QRuk3fKio34KLmRaO/Us3bnWGuzlOhACgIflqAUvz4Zm7Q5P34tgRd8euVg9MrNrG8zEQ1rre40ERJ",
	"F1c0GpZdckOUkMlUBwQVryjVXPXU7uOEibwClSQJ9NBP7BZmJoJqm+jO4VTZKx0UZSZEFDOlV2rNx+74",
	"Xg7BybjoPcXC9o06RSILZegW60opWAgWEiy10aADSQoUxsmEUBxbo8ov69VBGY1BCHSr3efGnPMWvMh7",
	"vpxZTo6DxSk/JTKu6V8tO0oL52rp14r88f18NYE+grHR2bXVub3mkgpN0EwAF8gM7kxahdK7NYPmldVX",
	"oM3X7/9ewYAxvirFXPRvSCp4R3MN7lINoDL552oe7HIruCFtdlFeygNFC0tGoJWlJNLOVG2dERM8aLH9",
	"NvLgO8dzsc6vQAdXF4fXhT/5OrhrgtVWdWlXtVzZFyugck+uTTJY2/Fp/cpu3k51Q+bFODTxSpmTBe2t",
	"RDIWbzXNc2ULylQe+2Y5CbY8WkQ4hJKZDKfNVbHKla4a9Z4Qd/dASefTXz7+9rS2OxTKpVWnHKPOnhmy",
	"zvbNf8sw6HhBE+eWS1NtUJFKr+5GsoYEPXU8oNsp0LwckUktiiCMMQeBjFrSA6r44gfd/IkdDcV4BDES",
	"KYRPm0LUlbo+K+ctPIIshGLeCZGA+/r/D/cb+9TzCVwsp9627p9bjjWHscaEcT/HdW9vr0nurRtUXuhi",
	"uw+x2iYAVgzf1cLChSv4lkQTkOvd3/zV9KlFA91urouHX/NZ/N1lZnebKUIzgt2GMp9635lNJNAq8mTq",
	"4eRZU9Zygr9MG9Kv8Rd1iJM/tXCfglZ2CUUhxLH4X4RHQh1EP7hSg9b4RAflXX3QMt3tsuluSSSnu5mN",
	"0KbF6VSxtRe3X55uv2W622XTrbq4Z+XZGilnHJveAWqZt4HPb5dxQoV39eC61oXOHyBybra7OabCEIQY",
	"SHYDNC9zOQVs6oVac8CcJza1r5T7mJIPYG9ukPbbRmFKtIJsbKdrihBC5oNgGQ8BJRAR/MN18CTlMAYu",
	"uiGLGe8a0XWIIsxvnl4HSPBQgPzhOj8OOL7tGV+wUpDt7S7/VkTMJkzfe+ibrWf/MxhhSoEP1NADqphm",
	"8GpvL/2izobrYFNAYzXQPUEqb4kefjCKM1gMLEkmCMdqenMkGoC+LTQGkn6F8tfU+l6O0hT9jCmeQKJ2",
	"TKL/aYz2mIwhnIcxdGxgUqecGr2Y0Ikyjct/6dJ09l8sTc2/jCu1g0CGOob3jnFEhMjUFCZ1JsyEUpBF",
	"B6UxYAFoRgQx8fJP74n8KRshDikTRCmTRUCl/eLNU8Q4+oMRij6xjKNjIkLGo6JnZH7QXQmdEQn9V79c",
	"yPc/38Lv06fGnHe6eDOSjs5OSpr9YTB7poQBS4HilASHwfPeXu+5DZLord13mfKNx9N7kDqtQCjbw783",
	"Fcdlv4ww+bZOrzKgqpNJS4OTqCj3V01V0cAUJdZbEi2KJv2W0qlt2RUNPWvFYdfoW68yeve5UqPw2d5e",
	"mzqRt+svKAZ01wm+X2WIRbextSB3YUBNRrNthDSEclX8jBFp3WcmE8k4/ixcKAE5ZZEwR4Nmln6WW4Gt",
	"fPPk8vT49GkDE9S8B8EmyGu6uns/WNPFi21eTeZZv5bjPWO8tyIGv5LobuGe87aasLeivHSAkqfzyHOQ",
	"WgvNZnnkWfPObBsqAIY9dFrKAdE/uSsqQyXQh6X7KfnQHZMKj4UpFyu06z2CVG0GGs7d0Ktt/Y23fV6h",
	"eGf7zjDPwd7B6syTVw24v72qL/NsvVcVp/VLmSKNHHcUhpBKNGJyqonoXXq3IZdqBbShKzBrKmi70P/Q",
	"jDVERjt0TuufLi/PXLVHzbr2jk+tuVDnMpKsYcKOn3ekk8VH4PvJhybU37Ur7s09QKdYojGLY3Yr1r5z",
	"uJitH56bHx8TO8kRgcQkFsVl6x1xtclBWihGbZqSVYeeuBiWEa/oEk+eKqi8SwPt8nYB+X/GhF7ouS7x",
	"5JFINlOc7hEKNp8oO2WG/ldLxl9wAnePgjVs8ZFdckfna0uBk/JNGP8eYkP1/RKm1npN5d+WN221ATa+",
	"Dy7VN/fX1pbL1c43UpQr5dLvX0feAEWdIGViHay4guilN6jW21LlF7Q24+eG2uyam9fAbakume76evWu",
	"5ZJcO6anW5A7ql3JiRVZPLdszNNC6xiGeWH5rcl6crwlVb0i949IShVwrUkeezvJBgnWk0HlUvsbyaBK",
	"rf7F8kNbsAW0y1e2xLRRq0JdhKMIlT40LPPnuV9+PNjumPtmArfwP5S9cSXEOTtnucB1b9L4L/vkrzXZ",
	"Z97eNrxrglLOZsS7HVKYetZL0dUZWe4tsCkWysobARraMXRO9yGq25mukIa+aGL7GStuEyMuh+bXKVA0",
	"tA9+/WAetyGithL9Zg0y2k8HEalfG8sfGDMukzIqmrRBi9gtzEX7zNoKfsr624srdPLeKjKy072uM29n",
	"3tIDPP366zt3222g4hGCVQ/Wxscydr8BG3fJwv1WklNLz8eV5VVepnsLrvIeqFyBTRpeI9zWHChXG39U",
	"Jy1Zm8ydf1Pnmk47SFmsX8S8Vwebl7sbkfEYONAQijowU2Jic8O6c9P6r+11Vt/3VBSVU8eHoirQGeGM",
	"6pDZDHOibD3hrbSHfuxNemj498vfhzk6OKQxDk2mt3nFUmcL/8koIAlfGoV/WbHYcof+R7gIUcxC/Tpo",
	"Nc1xoUKDZdiQ+GHK+COMCiQo9i+9SFlJrSzlWS8KZZpxv6HkNQ+Mbi1s3bMKj0nSGhIVASqdYSeqN4ol",
	"Q4mice0+AKEFpZYxSSYbn2GO5y4ZQOuW/1V/d6z+ahSXPaIG1/evrvzHKc21Z0u21Z0fi5RYskvXUr/7",
	"fqnM7dwGjaU9H/SU957Pe2TnfdlxUVChVutgPXJO9Rs5+rn+Vnq+med5llqJNMMhQRLFV7qve0t36Orr",
	"DJuunxlNUqDhs709dPphaB8uRSGLTCWIt+ZSjgHKjpxyFkKU8UKvVvPqhK1C0o4zmbUkTqlBqi8Ivpnr",
	"a1cPyGj+20Tbcdrz1Ts2PDrgM9rbMjU9VUEgm6RuyTNfj9FiNtmpxPjIdnEIVt6OyJKRCWLFhIKWlGLK",
	"bgs1Bmjk+Fqtx9xcxOG0llzUNR2VtaQbkjEadveHra856/maH8neL986KBKQt+Q/+0DiYxRxCl/bCbXi",
	"hkWj1royt11A/ZnnHUiNbRUdC8lG6k77Y0PbhuAeBxddSMxl376n3ReSpWszkj1Zc29ji3m8Mhe5R95y",
	"3WLD08f2Xk19P8vi+KO20vWrVvdvJtdftHtEXOGgqtzCq/KD+30RR7RqTCmHEMsiCWRjHepXGF2dIKVI",
	"lR0r30B3KnkQCwhvGb8xB10MExzOTfauUwUYdaUgZnu9g95zbXAD5jEBXhjM7xj3U2EzAWj4/sdL1KqM",
	"DrUHC3C0QKfznnncflNtx/g1he5e9bISBy/TzFqZegbmfqOLZ1Y1LdOghtIm9cXWxCi0F3cdF6fpmMTQ",
	"cOu24Shc+fGohjpOfgrW3W58vRuehj7hDB51vYuqZwxTnQtuisua6nX++ZQwWqGbufdWEjw+1d6D9B+I",
	"3CgSX3tj8p7yGePY3eMTBbgrLL//9QbmlUigjwcTbPPrX60rHLze+hbe5800rvwNukd0IhoEIVwhwCL8",
	"d1ZjuYfCc/Wh18eWvLsWpq3d0hQ4uRdkbyaH13rSdicyupHIGxst9xONWYfSSqblVRGaE4vOmFDc44If",
	"kqE0i2PvgpKN+mBXn5xlIp4bN8RoboIkWgcYkEgMUdcMYDvl5ZJK2dlOZTg5Fm4MXdRqeV9T81Q3Rk/0",
	"OzMlfXMOsilHrnh6dxv9TWwoNryHf3fPE5Z6Ix1+07hzhLQ4U3q4W7xjEw1PlUvs7e9GGWzvhK2/+uIG",
	"130EqIEr6uiSboyWC/Qu2xK3MOrjNJ1wU/Ki7dyxJSI203EqL6D74DeXi8jp4z7WoVZb0MtZ3zI9+2JO",
	"w/+maN9zirayhBWil91ALdV30GTwKzt8+qxwbS5CGDLp1yWD/uyZ4ohBkl8010SxE9WfctTTaYvbbpxM",
	"mGc6rbFV2TF1N3Z5CAOisg11ZoiX9+xKT1RXunhEvQxTEKowZ/KSAh6Ynntt5VHLtm3juFWLdqORc6Hr",
	"nmr0ZO7iIWvCoTRMVTTURzKFG0xVuGMYE6pr89i6z+cw/uF6+ct61wHqG+dKnY62lPaupi3M4qZJvfD7",
	"7qf0r/cvBqDyhse9grMiJDsFwi/m3QxB7RHK3U+/GAXVVjsEoVyqu2nyykvTu5rWq4fcNG/1qehdTVwp",
	"DNg0df2J6F1NXqnr3jR5/W3x3W+46rMai/dd7QmabwFS8UrLesBV3rb5JmAW75tsAGvlCZ0vXYkn7znL",
	"UqPG2EF+tudeq4bfqSscnZqy0Gk45js1u6iTz3phH+ev62/WNPLSTVvPjE5LsY2GlxQ8aVOtml6v6ll/",
	"KaEMvmXXWmxyMdus85zNwpeaPt99vvv/AAAA///0TjZnuqUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
